BEGIN;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone_number INTEGER NOT NULL,
  password VARCHAR(100) NOT NULL,
  banned BOOLEAN NOT NULL default false
);

DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL,
    description VARCHAR(250) NOT NULL

);
DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  product_id INTEGER REFERENCES products(id),
  amount INTEGER NOT NULL,
  notes VARCHAR(250) NOT NULL

);
DROP TABLE IF EXISTS suggestions CASCADE;
CREATE TABLE suggestions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  suggestion VARCHAR(250) NOT NULL

);



COMMIT;
